//draw_self_z()
draw_sprite_ext(sprite_index,
                image_index,
                round(x),
                round(y-z),
                image_xscale,
                image_yscale,
                image_angle,
                image_blend,
                image_alpha);
